sudo: required

# matrix layout based on:
# https://github.com/libressl-portable/portable/blob/9e090286b55def5ca2c0cc375c65023a70d8796e/.travis.yml

matrix:
  include:
    - {env: IMPL=clojure,  services: [docker]}

script:
  # Build
  - ./.travis_build.sh

  # Regular tests
  - ./.travis_test.sh test ${IMPL}
  - cat test.err || true

  # NOTE: use self-host-test branch
  # Self-hosted tests
  #- ./.travis_test.sh test mal ${IMPL}
  #- cat test.err || true; rm -f test.err

  # Performance tests
  - if [ -z "${NO_PERF}" ]; then ./.travis_test.sh perf ${IMPL}; fi
  - cat perf.err || true
